"""
unifi_poller — polls UniFi Controller every 60 seconds for switch port stats
and connected client inventory, then writes to the collector buffer
(→ Railway backend).

Switch port stats  → /api/collector/metrics/ports  (via buffer)
Connected clients  → /api/collector/metrics/devices (via buffer)

Environment variables:
  BACKEND_URL       — https://<railway-app>.railway.app
  UNIFI_URL         — e.g. https://192.168.1.1
  UNIFI_PORT        — default 8443
  UNIFI_USER        — local UniFi account username
  UNIFI_PASS        — local UniFi account password
  UNIFI_SITE        — default
  UNIFI_VERIFY_SSL  — false (self-signed cert)
  POLL_INTERVAL     — seconds between polls (default 60)
"""

import sys
sys.path.insert(0, '/app')

import logging
import os
import threading
import time
import time as _time_module
from datetime import datetime, timezone

import requests

from buffer import write_local, flush_to_backend

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
log = logging.getLogger(__name__)

# ── Config ────────────────────────────────────────────────────────────────────

BACKEND_URL   = os.environ["BACKEND_URL"]
UNIFI_URL     = os.environ["UNIFI_URL"].rstrip("/")
UNIFI_PORT    = os.environ.get("UNIFI_PORT", "8443")
UNIFI_USER    = os.environ["UNIFI_USER"]
UNIFI_PASS    = os.environ["UNIFI_PASS"]
UNIFI_SITE    = os.environ.get("UNIFI_SITE", "default")
VERIFY_SSL    = os.environ.get("UNIFI_VERIFY_SSL", "false").lower() not in ("false", "0", "no")
POLL_INTERVAL = max(60, int(os.environ.get("POLL_INTERVAL", "60")))

_BASE = f"{UNIFI_URL}:{UNIFI_PORT}"


# ── Delta tracking ────────────────────────────────────────────────────────────

# Module-level dict that persists across poll cycles within the same process.
# Resets to empty on container restart — first reading after restart produces
# zero deltas (safe: no false error spikes).
_prev_readings: dict[tuple, dict] = {}
# key: (switch_id, port_id)
# value: {"rx_bytes": int, "tx_bytes": int, "rx_errors": int, "tx_errors": int}


# ── Timestamp validation ──────────────────────────────────────────────────────

def _validate_now(now: str) -> bool:
    """Return True if `now` is within 300s of the current wall clock.

    This is a guard against clock-skew scenarios (e.g. NTP not yet synced).
    Under normal conditions `now` is generated by datetime.now(timezone.utc)
    immediately before calling _parse_switch_ports, so the drift will be < 1s.
    """
    try:
        row_ts = datetime.fromisoformat(now.replace("Z", "+00:00")).timestamp()
        return abs(_time_module.time() - row_ts) <= 300
    except Exception:
        return False


# ── UniFi session ─────────────────────────────────────────────────────────────

def _make_session() -> requests.Session:
    """Authenticate to the UniFi Controller and return an authenticated session."""
    session = requests.Session()
    session.verify = VERIFY_SSL

    resp = session.post(
        f"{_BASE}/api/login",
        json={"username": UNIFI_USER, "password": UNIFI_PASS},
        timeout=10,
    )
    resp.raise_for_status()
    log.info("Authenticated to UniFi Controller at %s", _BASE)
    return session


def _get(session: requests.Session, path: str) -> list[dict]:
    """GET /api/s/{site}/{path} and return the data list."""
    url = f"{_BASE}/api/s/{UNIFI_SITE}/{path}"
    resp = session.get(url, timeout=10)
    resp.raise_for_status()
    return resp.json().get("data", [])


# ── Switch port parsing ───────────────────────────────────────────────────────

def _build_port_map(stations: list[dict]) -> dict[tuple, dict]:
    """
    Build a (switch_mac, port_idx) → {device_name, device_ip} lookup from the
    connected-client list.  UniFi includes sw_mac / sw_port on wired clients,
    which is the only reliable way to know which device is on which port.
    """
    port_map: dict[tuple, dict] = {}
    for client in stations:
        sw_port = client.get("sw_port")
        sw_mac  = client.get("sw_mac", "").lower()
        if not sw_port or not sw_mac:
            continue
        name = (
            client.get("hostname")
            or client.get("name")
            or client.get("mac", "")
        )
        ip = client.get("ip", "").split("/")[0]  # strip /32 CIDR suffix if present
        port_map[(sw_mac, int(sw_port))] = {"device_name": name, "device_ip": ip or None}
    return port_map


def _parse_switch_ports(
    devices: list[dict],
    stations: list[dict],
    now: str,
) -> list[dict]:
    """
    Extract per-port metrics from USW (UniFi Switch) devices.
    Uses the connected-client list to resolve device_name and device_ip per port.
    Computes delta columns (rx/tx bytes and errors since last poll cycle).
    Returns rows ready for /api/collector/metrics/ports.
    """
    port_map = _build_port_map(stations)
    rows = []
    for device in devices:
        if device.get("type") != "usw":
            continue

        switch_id   = device.get("mac", "").lower()
        switch_name = device.get("name") or device.get("model", switch_id)

        for port in device.get("port_table", []):
            port_idx    = port.get("port_idx")
            client_info = port_map.get((switch_id, int(port_idx or 0)), {})
            port_label  = port.get("name", "") or f"Port {port_idx}"

            # Raw cumulative counters from UniFi (since switch boot)
            rx_bytes_raw  = port.get("rx_bytes")  or 0
            tx_bytes_raw  = port.get("tx_bytes")  or 0
            rx_errors_raw = port.get("rx_errors") or 0
            tx_errors_raw = port.get("tx_errors") or 0

            # Delta calculation against previous reading
            key  = (switch_id, port_idx)
            prev = _prev_readings.get(key)

            is_counter_reset = False
            if prev is not None:
                rx_bytes_delta  = rx_bytes_raw  - prev["rx_bytes"]
                tx_bytes_delta  = tx_bytes_raw  - prev["tx_bytes"]
                rx_errors_delta = rx_errors_raw - prev["rx_errors"]
                tx_errors_delta = tx_errors_raw - prev["tx_errors"]

                # Negative delta means the switch rebooted and counters wrapped.
                if rx_bytes_delta < 0 or tx_bytes_delta < 0 \
                        or rx_errors_delta < 0 or tx_errors_delta < 0:
                    is_counter_reset = True
                    rx_bytes_delta = tx_bytes_delta = 0
                    rx_errors_delta = tx_errors_delta = 0
                    log.info(
                        "Counter reset detected on switch=%s port=%s",
                        switch_id, port_idx,
                    )

                # Sanity guard: >10 GB transferred in one 60-second poll cycle
                # is physically impossible on a 1 Gbps port — discard the row.
                elif rx_bytes_delta > 10_000_000_000 or tx_bytes_delta > 10_000_000_000:
                    log.warning(
                        "Implausible delta on switch=%s port=%s (rx_delta=%d "
                        "tx_delta=%d) — discarding row",
                        switch_id, port_idx, rx_bytes_delta, tx_bytes_delta,
                    )
                    _prev_readings[key] = {
                        "rx_bytes":  rx_bytes_raw,
                        "tx_bytes":  tx_bytes_raw,
                        "rx_errors": rx_errors_raw,
                        "tx_errors": tx_errors_raw,
                    }
                    continue  # skip this row entirely
            else:
                # First reading after process start — no baseline yet.
                # Emit zeros so we don't fabricate a spike.
                rx_bytes_delta = tx_bytes_delta = 0
                rx_errors_delta = tx_errors_delta = 0

            # Persist current raw values as the new baseline for next cycle.
            _prev_readings[key] = {
                "rx_bytes":  rx_bytes_raw,
                "tx_bytes":  tx_bytes_raw,
                "rx_errors": rx_errors_raw,
                "tx_errors": tx_errors_raw,
            }

            rows.append({
                "time":             now,
                "switch_id":        switch_id,
                "switch_name":      switch_name,
                "port_id":          port_idx,
                "port_name":        port_label,
                "device_name":      client_info.get("device_name") or port_label,
                "device_ip":        client_info.get("device_ip"),
                "rx_bytes":         rx_bytes_raw,
                "tx_bytes":         tx_bytes_raw,
                "rx_errors":        rx_errors_raw,
                "tx_errors":        tx_errors_raw,
                "rx_packets":       port.get("rx_packets"),
                "tx_packets":       port.get("tx_packets"),
                "poe_watts":        port.get("poe_power"),
                "is_uplink":        port.get("is_uplink", False),
                # Delta columns (Phase 1A)
                "rx_errors_delta":  rx_errors_delta,
                "tx_errors_delta":  tx_errors_delta,
                "rx_bytes_delta":   rx_bytes_delta,
                "tx_bytes_delta":   tx_bytes_delta,
                "is_counter_reset": is_counter_reset,
            })
    return rows


# ── Device type detection ─────────────────────────────────────────────────────

# UniFi device type field → device_registry device_type
_UNIFI_DEVICE_TYPE_MAP: dict[str, str] = {
    "uap": "ap",
    "usw": "server",   # switches are critical infrastructure
    "ugw": "server",   # gateways are critical infrastructure
}

# Hostname substrings → device_type (checked case-insensitively, first match wins)
_HOSTNAME_PATTERNS: list[tuple[tuple[str, ...], str]] = [
    (("IPHONE", "IPAD", "GALAXY", "ANDROID", "WATCH", "PIXEL"), "mobile"),
    (("STAR-LT", "-LT-", "LAPTOP", "MACBOOK", "THINKPAD", "SURFACE"), "workstation"),
    (("STAR-D", "DESKTOP", "-PC-", "IMAC"), "workstation"),
    (("LT",), "workstation"),   # STAR naming: STAR-LT01, LT-JOHN, etc.
    (("PRINTER", "BRWA", "BROTHER", "HP-", "CANON", "RICOH", "XEROX"), "printer"),
    (("SERVER", "SRV-", "NAS", "SYNOLOGY", "QNAP", "FILESERVER"), "server"),
]


def _detect_client_type(hostname: str) -> str:
    """Infer device_type from a client hostname using STAR naming conventions."""
    if not hostname:
        return "unknown"
    h = hostname.upper()
    for substrings, dtype in _HOSTNAME_PATTERNS:
        if any(s in h for s in substrings):
            return dtype
    return "unknown"


# ── Client parsing ────────────────────────────────────────────────────────────

def _parse_clients(stations: list[dict]) -> list[dict]:
    """
    Map connected UniFi stations to device_registry upsert rows.
    Device type is inferred from hostname patterns; 'unknown' if no match.
    """
    rows = []
    for sta in stations:
        mac = sta.get("mac", "").lower()
        ip  = sta.get("ip", "").strip()
        if not mac or not ip:
            continue

        hostname = sta.get("hostname") or sta.get("name") or ""
        sw_mac   = sta.get("sw_mac", "").lower() or None
        sw_port  = sta.get("sw_port")
        rows.append({
            "mac":         mac,
            "ip":          ip,
            "hostname":    hostname,
            "device_type": _detect_client_type(hostname),
            "is_online":   True,
            "last_seen":   datetime.now(timezone.utc).isoformat(),
            "switch_id":   sw_mac,
            "port_id":     str(sw_port) if sw_port else None,
        })
    return rows


def _parse_infrastructure(devices: list[dict]) -> list[dict]:
    """
    Map UniFi infrastructure devices (APs, switches, gateways) to
    device_registry upsert rows, so they appear in the device list
    with the correct device_type.
    """
    rows = []
    for device in devices:
        dtype = _UNIFI_DEVICE_TYPE_MAP.get(device.get("type", ""))
        if not dtype:
            continue  # unknown device class — skip

        ip  = device.get("ip", "").strip()
        mac = device.get("mac", "").lower()
        if not ip or not mac:
            continue

        rows.append({
            "mac":         mac,
            "ip":          ip,
            "hostname":    device.get("name") or device.get("model", mac),
            "device_type": dtype,
            "is_online":   True,
            "last_seen":   datetime.now(timezone.utc).isoformat(),
        })
    return rows


# ── Buffer writes ─────────────────────────────────────────────────────────────

def _write_port_metrics(rows: list[dict]) -> None:
    if not rows:
        return
    for row in rows:
        write_local("/api/collector/metrics/ports", row)
    log.info("Buffered %d switch port rows", len(rows))


def _write_devices(rows: list[dict]) -> None:
    """Buffer device_registry upsert rows."""
    if not rows:
        return
    for row in rows:
        write_local("/api/collector/metrics/devices", row)
    log.info("Buffered %d device rows", len(rows))


# ── Background flush thread ───────────────────────────────────────────────────

def _flush_loop() -> None:
    """Background thread: flush buffer to backend every 20 seconds."""
    while True:
        time.sleep(20)
        try:
            flush_to_backend(BACKEND_URL)
        except Exception as exc:
            log.error("Flush error: %s", exc)


# ── Main loop ─────────────────────────────────────────────────────────────────

def main() -> None:
    log.info(
        "unifi_poller starting — controller=%s site=%s interval=%ds",
        _BASE, UNIFI_SITE, POLL_INTERVAL,
    )

    # Start background flush thread
    flush_thread = threading.Thread(target=_flush_loop, daemon=True)
    flush_thread.start()
    log.info("Buffer flush thread started (60s interval) → %s", BACKEND_URL)

    while True:
        start = time.monotonic()
        try:
            session = _make_session()

            now = datetime.now(timezone.utc).isoformat()

            # Guard against severely skewed clocks before writing any metrics.
            if not _validate_now(now):
                log.warning(
                    "Clock skew detected — generated timestamp %s is more than "
                    "300s from wall clock. Skipping write cycle.",
                    now,
                )
                continue

            # Fetch both endpoints; stations are needed for port→device mapping
            devices  = _get(session, "stat/device")
            stations = _get(session, "stat/sta")

            # Switch port stats (uses station list to resolve device_name/device_ip)
            port_rows = _parse_switch_ports(devices, stations, now)
            _write_port_metrics(port_rows)

            # Connected clients → device_registry upsert (with detected device types)
            client_rows = _parse_clients(stations)
            _write_devices(client_rows)

            # Infrastructure devices (APs, switches, gateways) → device_registry
            infra_rows = _parse_infrastructure(devices)
            _write_devices(infra_rows)

        except requests.HTTPError as exc:
            log.error("UniFi HTTP error: %s", exc)
        except requests.ConnectionError as exc:
            log.error("UniFi connection error: %s", exc)
        except Exception as exc:
            log.exception("Unexpected error: %s", exc)

        elapsed   = time.monotonic() - start
        sleep_for = max(0.0, POLL_INTERVAL - elapsed)
        time.sleep(sleep_for)


if __name__ == "__main__":
    main()
